In [37]:
# Task 1
my_file = open("Numbers.txt", "w")

my_file.write((str(3))) 
my_file.write(("\n"))
my_file.write((str(45)))
my_file.write(("\n"))
my_file.write((str(83)))
my_file.write(("\n"))
my_file.write((str(21)))
my_file.write(("\n"))
my_file.close()

In [20]:
#Task 2
my_mark = int(input("What is your mark on exam? "))

    
if my_mark > 80:
    print("Your grade is A* ")
elif my_mark >= 70:
    print("Your grade is A ")
elif my_mark >= 60:
    print("Your grade is B ")
elif my_mark >= 50:
    print("Your grade is C ")
elif my_mark >= 40:
    print("Your grade is D ")
else:
    print("Your grade is E ")
        
    print("Thank you for attending the exam. ")
    

Your grade is C 


In [21]:
# task 2 continue ... 
target_grade = int(input("What is yopur target grade? "))
if target_grade > my_mark:
    print("Try hard to score more. ")
elif target_grade == my_mark:
    print("Well done, you have hit the target.")
elif target_grade < my_mark:
    print("You have done an excellent result.")


You have done an excellent result.


In [39]:
#Create a 1D array of numbers from 0 to 9

import numpy as np  
my_array = np.arange(10)

print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [40]:
#Create a 3×3 NumPy array of all Boolean value Trues

my_array = np.ones(9, dtype=bool).reshape(3,3)

print(my_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [41]:
#Extract all odd numbers from array of 1-10
my_array = np.arange(1,10)
odd_nums = my_array[::2]

print(odd_nums)



[1 3 5 7 9]


In [42]:
#Replace all odd numbers in an array of 1-10 with the value -1
my_array = np.arange(1,10)
new_nums = my_array[::2] = -1


print(my_array)

[-1  2 -1  4 -1  6 -1  8 -1]


In [54]:
#Convert a 1D array to a 2D array with 2 rows
my_array = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,5)

print(my_array)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [52]:
#Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals
i = np.arange(1,10).reshape(3,3)
print(i)
j = np.arange(10,19).reshape(3,3)
print(j)
k = np.dot(i , j)
print(k)
l = np.sum(k)
print(l)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
1944


In [47]:

# numpy.repeat()
  
import numpy as geek
  

my_array = geek.arange(1,4)

    
repetitions = 3
a = geek.repeat(my_array, repetitions)

my_array2 = np.tile([1, 2, 3], 3) # repeats 123 three times

my_array3 = np.hstack((a, my_array2)) 

print( my_array3 )

#alternatively 
# one =np.ones(3)
# two = one + one
# three = one * 3
# repeat = np.arange(1,4)
# tile = np.tile(repeat, 3)
# final = np.concatenate((one, two, three, tile))
# print(final)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [56]:
#In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating  items present in array 
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
c = np.concatenate((a , b))

c = np.unique(c)
print(c)



[1 2 3 4 5 6 7 8 9]


In [49]:
# sum values of 3 to 7 together
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
c = np.concatenate((a ,b))
d = c[(3 <= c) & (c < 7)]
print(d)
print(sum(d))

[3 4 5 4 5 6]
27
